---

instance_groups:
  - name: concourse
    jobs:
      - name: web
        properties:
          github_auth:
            client_id: (( grab $GITHUB_CLIENT_ID ))
            client_secret: (( grab $GITHUB_CLIENT_SECRET ))
          main_team:
            auth:
              github:
                users:
                - 46bit
                - AP-Hunt
                - kr8n3r
                - LeePorte
                - mogds
                - paroxp
                - schmie
                - whi-tw
