---
instance_groups:
  - name: concourse
    jobs:
      - name: worker
        properties:
          baggageclaim:
            driver: overlay
  - name: concourse-worker
    jobs:
      - name: worker
        properties:
          baggageclaim:
            driver: overlay
