---
instance_groups:
  - name: concourse
    jobs:
      - name: worker
        properties:
          runtime: containerd
  - name: concourse-worker
    jobs:
      - name: worker
        properties:
          runtime: containerd
